/*******************************************************************************
 * Copyright 2017-2026 TAXTELECOM, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package org.pgcodekeeper.core.database.pg.parser.statement;

import java.util.List;

import org.antlr.v4.runtime.ParserRuleContext;
import org.pgcodekeeper.core.DangerStatement;
import org.pgcodekeeper.core.database.api.schema.*;
import org.pgcodekeeper.core.database.base.parser.QNameParser;
import org.pgcodekeeper.core.database.pg.parser.generated.SQLParser.*;
import org.pgcodekeeper.core.database.pg.schema.*;
import org.pgcodekeeper.core.exception.UnresolvedReferenceException;
import org.pgcodekeeper.core.settings.ISettings;

/**
 * Parser for PostgreSQL ALTER SEQUENCE statements.
 * <p>
 * This class handles parsing of sequence alterations including changing sequence
 * properties, ownership relationships, and logging behavior. It also handles
 * special cases for sequences generated by identity columns.
 */
public final class PgAlterSequence extends PgParserAbstract {

    private final Alter_sequence_statementContext ctx;

    /**
     * Constructs a new AlterSequence parser.
     *
     * @param ctx      the ALTER SEQUENCE statement context
     * @param db       the PostgreSQL database object
     * @param settings the ISettings object
     */
    public PgAlterSequence(Alter_sequence_statementContext ctx, PgDatabase db, ISettings settings) {
        super(db, settings);
        this.ctx = ctx;
    }

    @Override
    public void parseObject() {
        List<ParserRuleContext> ids = getIdentifiers(ctx.name);
        ObjectLocation loc = addObjReference(ids, DbObjType.SEQUENCE, ACTION_ALTER);
        var loggedCtx = ctx.set_logged();
        if (loggedCtx != null) {
            setLogged(loggedCtx, ids);
            return;
        }
        PgSequence sequence = getSafe(PgSchema::getSequence, getSchemaSafe(ids), QNameParser.getFirstNameCtx(ids));

        for (Sequence_bodyContext seqbody : ctx.sequence_body()) {
            if (seqbody.OWNED() != null && seqbody.col_name != null) {
                List<ParserRuleContext> col = getIdentifiers(seqbody.col_name);
                Tokens_nonreserved_except_function_typeContext word;
                if (col.size() != 1
                        || (word = seqbody.col_name.identifier().tokens_nonreserved_except_function_type()) == null
                        || word.NONE() == null) {
                    GenericColumn gc = new GenericColumn(QNameParser.getThirdName(col),
                            QNameParser.getSecondName(col), QNameParser.getFirstName(col), DbObjType.COLUMN);
                    doSafe(PgSequence::setOwnedBy, sequence, gc);
                    if (col.size() > 1) {
                        List<ParserRuleContext> tableIds = col.subList(0, col.size() - 1);
                        addObjReference(tableIds, DbObjType.TABLE, null);
                    }
                }
            }
        }

        if (!ctx.RESTART().isEmpty()) {
            loc.setWarning(DangerStatement.RESTART_WITH);
        }
    }

    /**
     * Searches column generated sequence and set to {@link PgSequence} field isLogged false. We must look for by
     * {@link PgColumn} field because generated sequence not be the child element of {@link AbstractSchema}
     *
     * @param loggedCtx - {@link Set_loggedContext}
     * @param ids       - list of {@link ParserRuleContext} where store {@link PgSequence} qualified name
     * @throws UnresolvedReferenceException if object not found or location is broken
     */
    private void setLogged(Set_loggedContext loggedCtx, List<ParserRuleContext> ids) {
        if (isRefMode()) {
            return;
        }

        boolean isLogged = loggedCtx.LOGGED() != null;

        var schema = getSchemaSafe(ids);
        var seqName = QNameParser.getFirstName(ids);
        var nameToken = QNameParser.getFirstNameCtx(ids).getStart();

        for (var table : schema.getTables()) {
            for (var column : table.getColumns()) {
                PgColumn col = (PgColumn) column;
                PgSequence seq = col.getSequence();
                if (seq != null && seqName.equals(seq.getName())) {
                    checkLocation(table, nameToken);
                    seq.setLogged(isLogged);
                    return;
                }
            }
        }

        throw new UnresolvedReferenceException("Cannot find object in database: " + seqName, nameToken);
    }

    @Override
    protected ObjectLocation fillQueryLocation(ParserRuleContext ctx) {
        ObjectLocation loc = super.fillQueryLocation(ctx);
        if (!((Schema_alterContext) ctx).alter_sequence_statement().RESTART().isEmpty()) {
            loc.setWarning(DangerStatement.RESTART_WITH);
        }
        return loc;
    }

    @Override
    protected String getStmtAction() {
        return getStrForStmtAction(ACTION_ALTER, DbObjType.SEQUENCE, getIdentifiers(ctx.name));
    }
}
