DELETE FROM table1 WHERE id = 1;
DELETE FROM mydb.mytable WHERE status = 'inactive';
DELETE FROM table1 ON CLUSTER cluster1 WHERE date < '2024-01-01';
DELETE FROM table1 ON CLUSTER 'my_cluster' WHERE timestamp < now();
DELETE FROM table1 IN PARTITION 2024 WHERE category = 'old';
DELETE FROM table1 IN PARTITION 'partition_name' WHERE flag = true;
DELETE FROM table1 ON CLUSTER cluster1 IN PARTITION 2024 WHERE id > 1000;
DELETE FROM table1 ON CLUSTER 'my_cluster' IN PARTITION 'part1' WHERE status = 'deleted';
DELETE FROM logs WHERE level = 'DEBUG' AND created < '2024-01-01';
DELETE FROM events ON CLUSTER dc1 WHERE user_id = 123 AND event_type = 'test';
DELETE FROM archive IN PARTITION '2023' WHERE processed = true;
DELETE FROM temp_data ON CLUSTER cluster1 IN PARTITION 'tmp' WHERE expires < now();
DELETE FROM users WHERE last_login < '2023-01-01' AND active = false;
DELETE FROM sessions ON CLUSTER replica1 IN PARTITION 'current' WHERE expired = 1;
DELETE FROM metrics WHERE value IS NULL AND timestamp < '2024-01-01';
-- DELETE FROM 02416_rocksdb WHERE 1 = 1;
-- DELETE FROM 02416_rocksdb WHERE value LIKE 'Some%string';
-- DELETE FROM 02418_test WHERE key <= 2;
-- DELETE FROM 02577_keepermap_delete_update WHERE value LIKE 'Some%string';
-- DELETE FROM 02581_trips WHERE id IN (SELECT (number*10 + 9)::UInt32 FROM numbers(200000000));
DELETE FROM lwd_test WHERE id >= 300000 and id < 400000;
DELETE FROM merge_table_standard_delete WHERE 1;
DELETE FROM replicated_table_r2 WHERE name IN ('1','2','3','4');
DELETE FROM t1_local ON CLUSTER test_shard_localhost WHERE tc1 = 1;
DELETE FROM test_apply_deleted_mask WHERE id % 2 = 0;