ALTER TABLE default.testtable ADD INDEX i_a (a) TYPE minmax GRANULARITY 4;
ALTER TABLE default.testtable ADD INDEX i_b (b) TYPE bloom_filter(0.025) GRANULARITY 2;
ALTER TABLE default.testtable ADD INDEX idx2 (date(ts)) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab1 ADD INDEX idx_tab1_0 (col0) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab1 ADD INDEX idx_tab1_1 (col1) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab1 ADD INDEX idx_tab1_3 (col3) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab1 ADD INDEX idx_tab1_4 (col4) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab2 ADD INDEX idx_tab2_0 (col0) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab2 ADD INDEX idx_tab2_1 (col0, col1) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab2 ADD INDEX idx_tab2_2 (col0, col1, col4) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab2 ADD INDEX idx_tab2_3 (col0, col1) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab2 ADD INDEX idx_tab2_4 (col0, col3) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab2 ADD INDEX idx_tab2_5 (col0, col4) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab2 ADD INDEX idx_tab2_6 (col0, col4) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab3 ADD INDEX idx_tab3_1 (col3, col0) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab3 ADD INDEX idx_tab3_2 (col3, col0, col4) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab3 ADD INDEX idx_tab3_3 (col3, col0, col4) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab3 ADD INDEX idx_tab3_4 (col3, col1) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab4 ADD INDEX idx_tab4_5 (col4, col0) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab4 ADD INDEX idx_tab4_6 (col4, col1) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab4 ADD INDEX idx_tab4_7 (col4, col1, col3) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab4 ADD INDEX idx_tab4_8 (col4, col3, col1) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab4 ADD INDEX idx_tab4_9 (col4, col3) TYPE minmax GRANULARITY 1;
ALTER TABLE default.tab4 ADD INDEX IF NOT EXISTS i_a (a) TYPE minmax GRANULARITY 2;
ALTER TABLE default.tab4 DROP INDEX i_a;
ALTER TABLE default.tab4 DROP INDEX IF EXISTS i_a;