ALTER NAMED COLLECTION foobar03 DELETE b;
ATTACH TABLE `01686_test`;
ATTACH TABLE adaptive_granularity_alter1;
BEGIN TRANSACTION;
CHECK TABLE check_codec SETTINGS max_threads = 1;
CHECK TABLE check_query_log;
CHECK TABLE check_query_test SETTINGS max_threads = 1;
CHECK TABLE check_query_test_non_adaptive SETTINGS max_threads = 1;
CHECK TABLE check_query_tiny_log SETTINGS max_threads = 8, check_query_single_value_result = 0 FORMAT Null;
CHECK TABLE check_query_tiny_log PARTITION tuple();
CHECK TABLE check_query_tiny_log;
CHECK TABLE check_table_with_indices SETTINGS max_threads = 1;
CHECK TABLE merge_table_standard_delete;
CHECK TABLE mt_table PART '201801_1_1_0';
CHECK TABLE mt_table PARTITION 201902 SETTINGS max_threads = 1;
CHECK TABLE mt_table SETTINGS max_threads = 1;
CHECK TABLE mt_without_pk SETTINGS max_threads = 1;
CHECK TABLE replicated_mt_without_pk SETTINGS max_threads = 1;
CHECK TABLE sqllt.table FORMAT Null;
CHECK TABLE t_large;
CHECK TABLE t_light;
CHECK TABLE t_source_part_is_intact SETTINGS max_threads = 1;
CHECK TABLE t_sparse_02235 SETTINGS check_query_single_value_result = 0, max_threads = 1;
check table tp settings check_query_single_value_result=0, max_threads=1;
commit;
CREATE NAMED COLLECTION `02918_json_fuzzer` AS json_str='{}';
CREATE OR REPLACE DICTIONARY test_01915_db.test_dictionary (   id UInt64,   value String ) PRIMARY KEY id LAYOUT(DIRECT()) SOURCE(CLICKHOUSE(DB 'test_01915_db' TABLE 'test_source_table_1'));
CREATE OR REPLACE DICTIONARY test_01915_db.test_dictionary (   id UInt64,   value_1 String ) PRIMARY KEY id LAYOUT(HASHED()) SOURCE(CLICKHOUSE(DB 'test_01915_db' TABLE 'test_source_table_2')) LIFETIME(0);
CREATE OR REPLACE TABLE alias_local10 (  Id Int8,  EventDate Date DEFAULT '2000-01-01',  field1 Int8,  field2 String,  field3 ALIAS CASE WHEN field1 = 1 THEN field2 ELSE '0' END ) ENGINE = MergeTree(EventDate, (Id, EventDate), 8192);
CREATE OR REPLACE TABLE distributed (x Array(Int8)) ENGINE = Distributed(test_shard_localhost, currentDatabase(), local);
create or replace table t1 (n UInt64, s Nullable(String)) engine=MergeTree order by n;
create or replace table t1 (n UInt64, s String) engine=MergeTree order by n;
DESC (SELECT * FROM HASH_MV);
desc (select * from system.numbers);
desc (select 1);
DESC alter_test;
desc file('02374_data1.jsonl');
desc file('02374_data2.jsonl');
desc table (select 1);
DESC TABLE `02483_substitute_udf`;
DESC TABLE add_materialized_column_after;
desc test format TSVRaw;
desc test_array_tuple;
desc test_nested;
DESC tuple;
desc url('http://localhost:8888/test/data.tsv?get=parameterHere', auto, 'x UInt32');
desc urlCluster('test_cluster_two_shards_localhost', 'http://localhost:11111/test/{a,b,c}.tsv', 'TSV', 'c1 UInt64, c2 UInt64, c3 UInt64');
desc urlCluster('test_cluster_two_shards_localhost', 'http://localhost:11111/test/{a,b,c}.tsv', 'TSV', 'c1 UInt64, c2 UInt64, c3 UInt64', 'auto');
DESCRIBE (SELECT 'test');
DESCRIBE (SELECT (1, 1));
DESCRIBE (WITH x -> x + 1 AS test_lambda SELECT test_lambda(1));
DESCRIBE remote(default, currentDatabase(), t_describe_options) FORMAT PrettyCompactNoEscapes;
DESCRIBE t_ephemeral_02205_1;
DESCRIBE TABLE `02266_auto_add_nullable`;
DESCRIBE test;
DETACH TABLE `02181_test_dictionary`;
detach table `02681_undrop_detach` sync;
DETACH TABLE adaptive_granularity_alter1;
DETACH TABLE adaptive_granularity_alter2;
drop table if exists order_test1;
DROP NAMED COLLECTION IF EXISTS `02918_json_fuzzer`;
drop temporary table wups;
EXISTS TABLE aine;
EXCHANGE DICTIONARIES `01914_db`.dictionary_1 AND `01914_db`.dictionary_2;
EXPLAIN (SELECT 1 UNION DISTINCT SELECT 1) UNION DISTINCT SELECT 1;
EXPLAIN actions=0, description=0, header=1 SELECT * FROM ( SELECT 'key2' AS key ) AS s1 JOIN ( SELECT 'key1' AS key, '1' AS value UNION ALL SELECT 'key2' AS key, '1' AS value ) AS s2 USING (key);
explain description=0 select * from remote('127.{1,2}', view(select * from numbers(1e6))) order by number limit 10 settings distributed_push_down_limit=1;
EXPLAIN ESTIMATE SELECT 1 IN (SELECT joinGet(`02843_join`, 'value', materialize(1)));
explain header = 1 select 1 as x;
explain indexes = 1 select * from test1 where a > 10 settings allow_experimental_analyzer = 0;
EXPLAIN PIPELINE graph = 1, compact = 1 SELECT * FROM merge1 SETTINGS allow_experimental_analyzer=1 FORMAT Null;
EXPLAIN PLAN SELECT * FROM test_order_by ORDER BY timestamp LIMIT 10;
EXPLAIN QUERY TREE (SELECT sum(if((number % 2) == 0, 0, 1)) FROM numbers(10));
EXPLAIN SELECT 1 UNION (SELECT 1 UNION ALL SELECT 1);
OPTIMIZE TABLE merge_tree_deduplication FINAL;
rename table db_hang.test to db_hang_temp.test;
RENAME DATABASE db_hang_temp TO new_database_name;
RENAME dictionary OLD_DICT TO NEW_DICT;
REPLACE DICTIONARY `01913_db`.test_dictionary (   id UInt64,   value_1 String ) PRIMARY KEY id LAYOUT(HASHED()) SOURCE(CLICKHOUSE(DB '01913_db' TABLE 'test_source_table_2')) LIFETIME(0);
replace table buf (n int) engine=Buffer(currentDatabase(), dist, 1, 10, 100, 10, 100, 1000, 1000);
replace table join engine=Join(ANY, INNER, n) as select * from t where throwIf(n);
replace table t1 (n UInt64) engine=MergeTree order by n;
replace table t1 (n UInt64, s String) engine=MergeTree order by n;
rollback;
SET wait_for_async_insert = 0;
system flush distributed t_l5ydey;
SYSTEM FLUSH DISTRIBUTED test_dist_02536;
SYSTEM FLUSH LOGS;
system flush logs;
SYSTEM RELOAD DICTIONARIES;
system reload dictionaries;
SYSTEM RELOAD DICTIONARY dict;
system start distributed sends dist_01293;
SYSTEM START FETCHES quorum1;
system start ttl merges ttl;
system start ttl merges ttl_test_02129;
truncate table arr_tests_visits;
truncate temporary table test_00670;
TRUNCATE test_table;
truncate trunc;
TRUNCATE truncate_test;
SYSTEM FLUSH DISTRIBUTED my_dist ON CLUSTER my_cluster;
SYSTEM FLUSH DISTRIBUTED db.my_dist SETTINGS max_threads = 4;
SYSTEM FLUSH DISTRIBUTED db.my_dist ON CLUSTER my_cluster SETTINGS max_threads = 4;
SYSTEM FLUSH LOGS ON CLUSTER my_cluster;
SYSTEM FLUSH LOGS query_log, trace_log;
SYSTEM FLUSH LOGS ON CLUSTER my_cluster query_log, db.custom_log;
SYSTEM DROP DNS CACHE;
SYSTEM DROP MARK CACHE;
SYSTEM DROP ICEBERG METADATA CACHE;
SYSTEM DROP TEXT INDEX DICTIONARY CACHE;
SYSTEM DROP TEXT INDEX HEADER CACHE;
SYSTEM DROP TEXT INDEX POSTINGS CACHE;
SYSTEM DROP TEXT INDEX CACHES;
SYSTEM DROP UNCOMPRESSED CACHE;
SYSTEM DROP COMPILED EXPRESSION CACHE;
SYSTEM DROP QUERY CONDITION CACHE;
SYSTEM DROP QUERY CACHE;
SYSTEM DROP QUERY CACHE TAG 'my_tag';
SYSTEM DROP FORMAT SCHEMA CACHE;
SYSTEM DROP FORMAT SCHEMA CACHE FOR PROTOBUF;
SYSTEM DROP FORMAT SCHEMA CACHE FOR FILES;
SYSTEM DROP FILESYSTEM CACHE;
SYSTEM DROP FILESYSTEM CACHE ON CLUSTER my_cluster;
SYSTEM DROP REPLICA 'replica1';
SYSTEM DROP REPLICA 'replica1' FROM DATABASE db1;
SYSTEM DROP REPLICA 'replica1' FROM TABLE db1.table1;
SYSTEM DROP REPLICA 'replica1' FROM ZKPATH '/clickhouse/tables/01/table1';
SYSTEM DROP DATABASE REPLICA 'replica1';
SYSTEM DROP DATABASE REPLICA 'replica1' FROM SHARD 'shard1';
SYSTEM DROP DATABASE REPLICA 'replica1' FROM DATABASE db1;
SYSTEM DROP DATABASE REPLICA 'replica1' FROM SHARD 'shard1' FROM DATABASE db1;
SYSTEM DROP DATABASE REPLICA 'replica1' FROM ZKPATH '/clickhouse/databases/db1';
SYSTEM DROP DATABASE REPLICA 'replica1' FROM SHARD 'shard1' FROM ZKPATH '/clickhouse/databases/db1';
SYSTEM START DISTRIBUTED SENDS db.my_dist ON CLUSTER my_cluster;
SYSTEM STOP DISTRIBUTED SENDS my_dist ON CLUSTER my_cluster;
SYSTEM STOP LISTEN QUERIES ALL;
SYSTEM STOP LISTEN QUERIES ALL EXCEPT system, metrics;
SYSTEM START LISTEN ON CLUSTER my_cluster QUERIES DEFAULT EXCEPT http_handler;
SYSTEM STOP LISTEN TCP;
SYSTEM STOP LISTEN TCP WITH PROXY;
SYSTEM STOP LISTEN TCP SECURE;
SYSTEM STOP LISTEN HTTP;
SYSTEM STOP LISTEN HTTP SECURE;
SYSTEM STOP LISTEN HTTPS;
SYSTEM STOP LISTEN MYSQL;
SYSTEM STOP LISTEN GRPC;
SYSTEM STOP LISTEN POSTGRESQL;
SYSTEM STOP LISTEN PROMETHEUS;
SYSTEM STOP LISTEN CUSTOM 'my_protocol';
SYSTEM START MERGES ON CLUSTER my_cluster;
SYSTEM STOP MERGES ON CLUSTER my_cluster db.my_table;
SYSTEM START MERGES ON CLUSTER my_cluster ON VOLUME my_volume;
SYSTEM STOP MERGES ON VOLUME my_volume;
SYSTEM START TTL MERGES ON CLUSTER my_cluster;
SYSTEM STOP TTL MERGES ON CLUSTER my_cluster db.my_table;
SYSTEM START MOVES ON CLUSTER my_cluster;
SYSTEM STOP MOVES ON CLUSTER my_cluster db.my_table;
SYSTEM WAIT LOADING PARTS ON CLUSTER my_cluster db.my_table;
SYSTEM LOAD PRIMARY KEY;
SYSTEM UNLOAD PRIMARY KEY;
SYSTEM LOAD PRIMARY KEY db.my_table;
SYSTEM UNLOAD PRIMARY KEY db.my_table;
SYSTEM START FETCHES ON CLUSTER my_cluster;
SYSTEM STOP FETCHES ON CLUSTER my_cluster db.my_table;
SYSTEM START REPLICATED SENDS ON CLUSTER my_cluster;
SYSTEM STOP REPLICATED SENDS ON CLUSTER my_cluster db.my_table;
SYSTEM START REPLICATION QUEUES ON CLUSTER my_cluster;
SYSTEM STOP REPLICATION QUEUES ON CLUSTER my_cluster db.my_table;
SYSTEM START PULLING REPLICATION LOG ON CLUSTER my_cluster;
SYSTEM STOP PULLING REPLICATION LOG ON CLUSTER my_cluster db.my_table;
SYSTEM SYNC REPLICA db.my_table;
SYSTEM SYNC REPLICA ON CLUSTER my_cluster db.my_table;
SYSTEM SYNC REPLICA db.my_table IF EXISTS;
SYSTEM SYNC REPLICA ON CLUSTER my_cluster db.my_table IF EXISTS;
SYSTEM SYNC REPLICA db.my_table STRICT;
SYSTEM SYNC REPLICA db.my_table LIGHTWEIGHT;
SYSTEM SYNC REPLICA db.my_table LIGHTWEIGHT FROM 'replica1';
SYSTEM SYNC REPLICA db.my_table LIGHTWEIGHT FROM 'replica1', 'replica2';
SYSTEM SYNC REPLICA db.my_table PULL;
SYSTEM SYNC REPLICA ON CLUSTER my_cluster db.my_table IF EXISTS LIGHTWEIGHT FROM 'replica1', 'replica2';
SYSTEM RESTART REPLICA ON CLUSTER my_cluster db.my_table;
SYSTEM RESTORE REPLICA db.my_table ON CLUSTER my_cluster;
SYSTEM RESTORE REPLICA ON CLUSTER my_cluster db.my_table;
SYSTEM RESTORE DATABASE REPLICA my_db;
SYSTEM RESTORE DATABASE REPLICA my_db ON CLUSTER my_cluster;
SYSTEM SYNC FILE CACHE;
SYSTEM SYNC FILE CACHE ON CLUSTER my_cluster;
SYSTEM START REPLICATED VIEW db.my_view;
SYSTEM STOP REPLICATED VIEW db.my_view;
SYSTEM REFRESH VIEW db.my_view;
SYSTEM WAIT VIEW db.my_view;
SYSTEM START VIEW db.my_view;
SYSTEM STOP VIEW db.my_view;
SYSTEM START VIEWS;
SYSTEM STOP VIEWS;
SYSTEM CANCEL VIEW db.my_view;
SYSTEM RESTART REPLICAS;
SYSTEM UNFREEZE WITH NAME 'my_backup';