SET search_path = pg_catalog;

ALTER TABLE public.t2
	ADD CONSTRAINT fk_complex_example FOREIGN KEY (b2, b3, PERIOD b1) REFERENCES public.t1(e1, e2, PERIOD e3) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED NOT ENFORCED;